app:
  name: cawe_dev_backend
  url: ${APPLICATION_URL:http://127.0.0.1:8080}
spring:
  profiles:
    active: ${PROFILE:dev}
  application:
    name: cawe
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none #Flyway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.${aws.cognito.region}.amazonaws.com/${aws.cognito.userPoolId}
  springdoc:
    swagger-ui:
      path: /swagger
      use-root-path: true
    redoc:
      path: /redoc.html
      enabled: true

aws:
  cognito:
    region: ${AWS_COGNITO_REGION:us-east-2}
    userPoolId: ${AWS_COGNITO_USER_POOL_ID}
    appClientId: ${AWS_COGNITO_APP_CLIENT_ID}
    user-info-uri: ${AWS_COGNITO_USER_INFO_URI}