version: '3.9'

services:
  postgres:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  cawe_dev_backend_app:
    build:
      context: ..
    image: cawe_dev_backend:dev
    ports:
      - "9901:8080"
    environment:
      PROFILE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      APPLICATION_SECURITY_JWT_SECRETKEY: ${APPLICATION_SECURITY_JWT_SECRETKEY}
      APPLICATION_SECURITY_JWT_EXPIRATION: ${APPLICATION_SECURITY_JWT_EXPIRATION}